apiVersion: v1
kind: Service
metadata:
  name: devops-demo-frontend-external
spec:
  type: NodePort
  selector:
    app: devops-demo-frontend
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: devops-demo-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-demo-frontend
  template:
    metadata:
      labels:
        app: devops-demo-frontend
    spec:
      imagePullSecrets:
      - name: sa-registry
      containers:
      - name: devops-demo-frontend
        image: mycluster.icp:8500/demo/devops-demo-frontend:0.6
        ports:
        - containerPort: 8080
        env:
        - name: BACKEND_HOST
          value: "devops-demo-backend-internal"
        - name: BACKEND_PORT
          value: "9080"