apiVersion: v1
kind: Service
metadata:
  name: APP_NAME-external
  labels:
    app: APP_NAME
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    instance-release: APPSELECTOR